forge 'http://forge.puppetlabs.com'

mod 'puppetlabs/stdlib', '4.15.0'
mod 'puppetlabs/inifile', '1.6.0'
mod 'puppetlabs/java_ks', '1.4.1'
mod 'puppetlabs/vcsrepo', '1.5.0'
mod 'abrader/gms', '1.0.3'
mod 'pltraining/rbac', '0.0.5'
mod 'stahnma/epel', '1.2.2'
mod 'puppet/archive', '1.3.0'
mod 'npwalker-pe_code_manager_webhook', '2.0.1'
mod 'crayfishx-firewalld', '3.1.8'
